# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='participants',
        ),
        migrations.AddField(
            model_name='game',
            name='playerA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PlayerA+', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='playerB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PlayerB+', to='player.Player'),
        ),
    ]
