# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190806_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='asked_questions',
            field=models.ManyToManyField(blank=True, to='question.Question'),
        ),
    ]
